version: "3.9"
services:
  web:
    #build: .
    image: node
    volumes:
      - .:/app
      - ./server:/server
    ports:
      - "3000:5173"
  server:
    image: "amazoncorretto:19"
    stdin_open: true
    tty: true
    volumes:
      - ./server:/server
    ports:
    #mc ports
      - "25565:25565/udp"
      - "25565:25565/tcp"
    #rcon ports
      - "25575:25575/udp"
      - "25575:25575/tcp"
    
    working_dir: /server
    command: java -Xmx${MAX_RAM:-1024M} -Xms${MIN_RAM:-1024M} -jar server.jar nogui